#! /bin/bash

chmod +x ./install/*

./install/node8
./install/docker

mkdir -p ~/router

ln -s $(pwd)/router-docker-compose.yml ~/router/docker-compose.yml

echo "Linked router docker container in ~/router."
echo "run \`docker-compose up -d\` in that directory"
echo "to start the dnsmasq container"
echo ""
echo "A reboot is most likely required."
