#!/bin/bash

dir=$(pwd)

rm -rf ~/.vim 2>/dev/null
ln -s $dir/vim ~/.vim

if ! hash curl 2>/dev/null; then
  sudo apt install curl -y
fi

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
sudo chmod u+x nvim.appimage

sudo mv nvim.appimage /usr/local/bin/nvim
sudo ln -s /usr/local/bin/nvim /usr/local/bin/vim

# Add neovim config
rm -rf ~/.config/nvim 2>/dev/null
ln -s $dir/.config/nvim ~/.config/nvim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

/usr/local/bin/nvim +PackerSync +qall

curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
sudo dpkg -i ripgrep_13.0.0_amd64.deb
rm ripgrep_13.0.0_amd64.deb

sudo apt install exuberant-ctags -y

echo "done"
