#!/bin/bash

if ! hash pip3 2>/dev/null; then
    sudo apt-get install python3-pip -y
fi

git clone https://github.com/b-ryan/powerline-shell

cd powerline-shell

sudo python3 setup.py install

cd ../

sudo rm -rf powerline-shell
