#!/bin/bash

action=$1

[ "$action" = "usage" ] && {
    echo "    $curcmd Displays all the lines in SRC file located in the todo.txt directory,"
    echo "      sorted by priority with line  numbers.  If TERM specified, lists"
    echo "      all lines that contain TERM(s) in SRC file.  Hides all tasks that"
    echo "      contain TERM(s) preceded by a minus sign (i.e. -TERM)."
    echo "      Without any arguments, the names of all text files in the todo.txt"
    echo "      directory are listed."
    exit
}

file=$2

"$TODO_SH" command lf "$file"
