#! /bin/bash

PLAYING=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json")
if [ -n "$PLAYING" ]; then
  ARTIST=$(jq .song.artist <<< $PLAYING)
  SONG=$(jq .song.title <<< $PLAYING)

  echo $ARTIST - $SONG
fi
