#! /bin/bash

echo "Installing docker with docker-compose"

if ! hash docker-compose 2>/dev/null; then
  sudo curl -L \
    https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` \
    -o \
    /usr/local/bin/docker-compose

  sudo chmod +x /usr/local/bin/docker-compose

  sudo curl -L \
    https://raw.githubusercontent.com/docker/compose/1.19.0/contrib/completion/bash/docker-compose \
    -o \
    /etc/bash_completion.d/docker-compose

  echo "Updating Apt"
  sudo apt-get update > /dev/null
fi

sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# bionic is not supported yet
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

sudo apt-get update

sudo apt-get install -y docker-ce
if ! [ $(getent group docker) ]; then
  sudo groupadd docker
fi

sudo usermod -aG docker $USER

sudo docker network create dockerbox
