#! /bin/bash
source ~/.bash_profile

if ! hash go 2>/dev/null; then
  wget https://dl.google.com/go/go1.18.linux-amd64.tar.gz
  sudo tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz

  rm go1.18.linux-amd64.tar.gz

  /usr/local/go/bin/go get -u github.com/derekparker/delve/cmd/dlv

  vim +GoInstallBinaries +qall
fi

if ! hash dep 2>/dev/null; then
  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
fi
