#! /bin/bash

sudo apt-get install -y nodejs

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" \
  | sudo tee /etc/apt/sources.list.d/yarn.list

echo "Updating Apt"
sudo apt-get update > /dev/null &&
sudo apt-get install yarn
