#! /bin/bash


wget https://nodejs.org/dist/v16.14.1/node-v16.14.1-linux-x64.tar.xz


tar -xvf node-v16.14.1-linux-x64.tar.xz
sudo chmod +x ./node-v16.14.1-linux-x64/bin/*
sudo mv ./node-v16.14.1-linux-x64/bin/* /usr/local/bin
sudo mv ./node-v16.14.1-linux-x64/lib/* /usr/local/lib

sudo rm -rf ./node-v16.14.1-linux-x64
