#! /bin/bash

if ! hash openvpn 2>/dev/null; then
  wget -O - https://swupdate.openvpn.net/repos/repo-public.gpg | sudo apt-key add -
  echo "deb [trusted=yes] http://build.openvpn.net/debian/openvpn/stable bionic main" | sudo tee /etc/apt/sources.list.d/openvpn-aptrepo.list
  sudo apt -y update
  sudo apt -y install openvpn easy-rsa
fi
