#! /bin/bash

if ! hash dunst 2>/dev/null; then
  sudo apt install \
    libdbus-1-dev \
    libx11-dev \
    libxinerama-dev \
    libxrandr-dev \
    libxss-dev \
    libglib2.0-dev \
    libpango1.0-dev \
    libgtk-3-dev \
    libxdg-basedir-dev \
    -y &&

  git clone https://github.com/dunst-project/dunst.git &&
  cd dunst
  make &&
  sudo make install &&
  cd ../
  rm -rf dunst
fi
