#! /bin/bash

sudo add-apt-repository ppa:aguignard/ppa -y
sudo apt-get update

sudo apt-get install \
  acpi \
  autoconf \
  libxcb1-dev \
  libxcb-keysyms1-dev \
  libpango1.0-dev \
  libxcb-util0-dev \
  libxcb-icccm4-dev \
  libyajl-dev \
  libstartup-notification0-dev \
  libxcb-randr0-dev \
  libev-dev \
  libxcb-cursor-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  libxcb-xrm-dev \
  libxcb-xrm-dev \
  lxappearance \
  xautolock \
  compton \
  shutter \
  -y

git clone https://www.github.com/Airblader/i3 i3-gaps

cd i3-gaps

autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/

../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make
sudo make install

cd ../../
rm -rf i3-gaps


git clone git://github.com/vivien/i3blocks
cd i3blocks
sudo make clean debug
sudo make install
sudo wget -O /usr/local/libexec/i3blocks/openvpn \
  https://raw.githubusercontent.com/vivien/i3blocks-contrib/master/openvpn/openvpn

cd ../
rm -rf i3blocks
