#! /bin/bash

sudo add-apt-repository xenial ppa:aguignard/ppa -y
sudo apt-get update

#####################
## Install i3 deps ##
#####################
sudo apt install \
  acpi \
  autoconf \
  help2man \
  libxcb1-dev \
  libxcb-keysyms1-dev \
  libpango1.0-dev \
  libxcb-util0-dev \
  libxcb-icccm4-dev \
  libyajl-dev \
  libstartup-notification0-dev \
  libxcb-randr0-dev \
  libev-dev \
  libxcb-cursor-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  libxcb-xrm-dev \
  libxcb-xrm-dev \
  lxappearance \
  -y


##############################################
## Install light to manage screen bightness ##
##############################################
git clone https://github.com/haikarainen/light.git
cd light
sudo make
sudo make install
cd ../
rm -rf light

#######################
## Build i3 from src ##
#######################
git clone https://www.github.com/Airblader/i3 i3-gaps

cd i3-gaps

autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/

../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make
sudo make install

cd ../../
rm -rf i3-gaps


##############################################
## Install Lightweight support applications ##
##############################################
sudo add-apt-repository ppa:font-manager/staging
sudo apt-get update

sudo apt install \
  i3lock \
  thunar \
  pavucontrol \
  xautolock \
  shutter \
  compton \
  font-manager \
  arandr \
  -y
