#! /bin/bash

sudo apt install \
  cmake \
  mpd \
  libpulse-dev \
  python-xcbgen \
  xcb-proto \
  libxcb-* \
  libiw-dev \
  libmpdclient-dev \
  libcurl4-gnutls-dev \
  libasound2-dev \
  -y

sudo apt install cmake
git clone --recursive https://github.com/jaagr/polybar
cd polybar && ./build.sh
cd ../ && rm -rf polybar
