export TERM=xterm-256color
export EDITOR=nvim
export GIT_EDITOR=nvim

export GOPATH=$HOME/go
export GOROOT=/usr/local/go
export GO111MODULE=auto
export PATH=$PATH:/usr/local/go_appengine
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$HOME/.node_modules/bin
export PATH=$PATH:$(python -m site --user-base)/bin
export PATH="$PATH:~/Library/Python/3.8/bin"
export BASH_SILENCE_DEPRECATION_WARNING=1

export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";

export HOST_IP=localhost 
export PORT=:8090 
export GITLAB_USER=JMeyering
export PATH=~/bin:$PATH

eval "$(rbenv init - bash)"


if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

if [ -f ~/.gitlabconfig ]; then
    . ~/.gitlabconfig
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

if [ -f "${HOME}/.gpg-agent-info" ]; then
  . "${HOME}/.gpg-agent-info"
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
  export SSH_AGENT_PID
fi

export GPG_TTY=$(tty)

gittag() {
  tag=$1
  git tag -d $tag
  git push origin :refs/tags/$tag
  git tag $tag
  git push && git push origin refs/tags/$tag
}

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

. ~/.personal
