#!/bin/bash
############################
# link
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=$(pwd)

dotfiles="bashrc bash_aliases bash_profile"    # list of filesto symlink in homedir


# Install basic applications
./install/powerline-shell
./install/nvim

#Create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $dotfiles; do
    rm ~/.$file 2>/dev/null

    ln -s $dir/$file ~/.$file 2>/dev/null
done


source ~/.bashrc

echo "done"
