#!/bin/bash
############################
# link
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=$(pwd)

dotfiles="bashrc gitconfig bash_aliases bash_profile"    # list of filesto symlink in homedir


#Dependencies

sudo su

if ! hash pip3 2>/dev/null; then
    sudo apt-get install python3-pip -y
fi

if ! hash nvim 2>/dev/null; then
    echo "Installing NeoVim"
    sudo add-apt-repository -yu ppa:neovim-ppa/stable >/dev/null &&

    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    sudo chmod u+x nvim.appimage
    sudo mv nvim.appimage /usr/local/bin
    sudo apt install ruby-full -y &&
    sudo apt install neovim -y &&

    #Install python and ruby bindings for neovim
    pip3 install neovim &&
    sudo gem install neovim
fi


#Create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $dotfiles; do
    rm ~/.$file 2>/dev/null

    ln -s $dir/$file ~/.$file 2>/dev/null
done

rm -rf ~/.vim 2>/dev/null
ln -s $dir/vim ~/.vim

# Add neovim config
rm -rf ~/.config/nvim 2>/dev/null
ln -s $dir/.config/nvim ~/.config/nvim

#Install VimPlug
if ! [ -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
    if ! hash curl 2>/dev/null; then
      sudo apt-get install curl -y
    fi
    echo "Installing VimPlug"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugInstall +qall

source ~/.bashrc

echo "done"
