#! /bin/bash

dir=$(pwd)

chmod +x install/*

sudo apt-get update -y

install/dunst &&
install/rofi &&
install/nitrogen &&
install/arc-theme &&
install/rxvt &&
install/i3

rm ~/.Xresources
rm ~/.i3blocks.conf
rm -rf ~/.config/dunst
rm -rf ~/.config/i3
rm -rf ~/.config/nitrogen
rm ~/.config/compton.conf

ln -s $dir/.Xresources ~/.Xresources
ln -s $dir/.config/compton.conf ~/.config/
ln -s $dir/.i3blocks.conf ~/

ln -s $dir/.config/dunst ~/.config/
ln -s $dir/.config/i3 ~/.config/
ln -s $dir/.config/nitrogen ~/.config/
