#! /bin/bash

dir=$(pwd)

chmod +x install/*

sudo apt-get update -y

install/dunst &&
install/polybar &&
install/rofi &&
install/nitrogen &&
install/rxvt &&
install/arc-theme &&
install/playerctl &&
install/i3 &&
install/acpi-events

rm ~/.Xresources
rm -rf ~/.config/dunst
rm -rf ~/.config/i3
rm -rf ~/.config/polybar
rm -rf ~/.config/nitrogen
rm ~/.config/compton.conf
sudo rm /etc/dnsmasq.d/test

ln -s $dir/bluetooth/audio.conf /etc/bluetooth/
ln -s $dir/.Xresources ~/.Xresources
ln -s $dir/.config/compton.conf ~/.config/
sudo ln -s $dir/dnsmasq-test.conf /etc/dnsmasq.d/test


ln -s $dir/.config/dunst ~/.config/
ln -s $dir/.config/i3 ~/.config/
ln -s $dir/.config/nitrogen ~/.config/
ln -s $dir/.config/polybar ~/.config/

sudo service dnsmasq restart
sudo /etc/init.d/dnsmasq restart
